
import { DiagnosticsMetrics } from '../types';

export const INITIAL_DIAGNOSTICS: DiagnosticsMetrics = {
    sdnn: 0, rmssd: 0, sdsd: 0, nn50: 0, pnn50: 0, meanRr: 0, meanHr: 0, sdnnIndex: 0,
    cv: 0, rrRange: 0,
    vlf: 0, lf: 0, hf: 0, lfHfRatio: 0, totalPower: 0, lfNu: 0, hfNu: 0, respRate: 0, mainPeak: 0, coherenceScore: 0,
    sd1: 0, sd2: 0, sd1Sd2Ratio: 0, cvi: 0, csi: 0, sampEn: 0, alpha1: 0, alpha2: 0, 
    vagalEfficiency: 0,
    hti: 0, tinn: 0, stressIndex: 0, portaIndex: 50, guzikIndex: 50, mad: 0, pas: 0,
    timeIrreversibility: 0, 
    skewness: 0, kurtosis: 0, turningPointRatio: 0,
    cepstralGamitude: 0, peakQuefrency: 0, spectralEntropy: 0, harmonicComplexity: 0,
    fundamentalFreq: 0, phiRatio: 0, recursionDepth: 0, implosionIndex: 0,
    mayerPower: 0, mayerPeak: 0, mayerPurity: 0,
    harmonicRoot: "C", harmonicInterval: "--", harmonicRatio: 1, harmonicCents: 0,
    harmonicAccuracy: 0, harmonicConsonance: 0, harmonicBaseHz: 0, harmonicTargetHz: 0,
    harmonicTuningSystem: "JUST_INTONATION",
    schumannLockScore: 0, schumannHarmonic: 0, schumannType: 'NONE', schumannTarget: 7.83, schumannDeviation: 0,
    zpScore: 0, zpRefraction: 0, zpState: 'CALIBRATING', zpPhase: 'IDLE', noise_level_mv: 0,
    carrierAmp: 0, carrierJitter: 0, carrierIntegrity: 0, carrierState: 'BUFFERING',
    qtc: 0, qrsDuration: 0, qtState: 'NORMAL',
    somaticScore: 0, somaticJerk: 0, somaticState: 'CALIBRATING', somaticIntegration: 0,
    accTotalPower: 0, accX: 0, accY: 0, accZ: 0, contractility: 0,
    pepLatency: 0, mechRespRate: 0, mechRespAmp: 0, swayFreq: 0, swayCoherence: 0, swayAmplitude: 0,
    microTremor: 0, postureAngle: 0, verticalOscillation: 0, kineticState: 'STILL',
    inspiratoryDutyCycle: 0,
    vagalLogRmssd: 0, vagalZScore: 0, vagalPhysioAge: 30, vagalState: 'CALIBRATING',
    baevskyMode: 0, baevskyAmplitude: 0, baevskyRange: 0, baevskyZone: 'READY',
    readinessAlpha: 1, readinessScore: 0, readinessZone: 'CALIBRATING', readinessArtifacts: 0,
    lorenzDimension: 0, lorenzDensity: 0, lorenzState: 'CALIBRATING',
    fftAlgorithm: "Cooley-Tukey", fftWindow: "Hanning", fftDetrend: "Linear", fftInterpolation: "Cubic",
    signalQualityIndex: 0,
    ecgSource: "Waiting...", ecgProtocol: "--", ecgSampleRate: 0, ecgGain: 0,
    telemetry: { batteryLevel: 100, temperature: 37, rssi: -60 },
    decelerationCapacity: 0, accelerationCapacity: 0,
    prsaCurve: [], turbulenceOnset: 0, turbulenceSlope: 0, cpcCoherence: 0, cpcSpectrum: [],
    pulseTransitTime: 0,
    lmsNoiseReductionDb: 0,
    hysteresisArea: 0, recoveryElasticity: 0, lissajousLock: 0
};
